# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
cache: packages

r_github_packages:
  - r-lib/pkgdown
  - tidyverse/tidytemplate

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE, run_dont_run = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.2

# To prevent "unable to verify current time" on travis R-devel
env:
  global:
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
